name: Static analysis
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    name: Analyze Dart
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: feeder
        run: dart pub get
      - name: Analyze Dart
        working-directory: feeder
        run: dart analyze